DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS DEALS;
DROP TABLE IF EXISTS SETTINGS;

CREATE TABLE TAGS
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag VARCHAR(5) UNIQUE,
    is_active BOOLEAN BOOLEAN NOT NULL,
    timestamp VARCHAR(25),
    description VARCHAR(100)
);

CREATE TABLE DEALS
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag VARCHAR(5),
    is_active BOOLEAN NOT NULL,
    timestamp VARCHAR(25),
    description VARCHAR(100),
    FOREIGN KEY (tag) REFERENCES TAGS(tag)
);

CREATE TABLE SETTINGS
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(25) UNIQUE NOT NULL,
    value VARCHAR(25) NOT NULL
)