bot:
  token: ""
  botName: ""
  proxyHost: ""
  proxyPort: 0
  proxyType: "HTTP"
  proxyEnabled: false

spring:
  datasource:
    url: jdbc:sqlite:dealbot.db
  flyway:
    user: sa
    password: sa
    schemas: main
    url: ${spring.datasource.url}
    locations: 'classpath:/db/init'
    enabled: true
    clean-on-validation-error: true