bot:
  token: "1022104603:AAH972QaQOgjDnTZh5oIWtMcvkA6-v6jlwg"
  botName: "HomeDealBot"
  proxyHost: "81.210.32.101"
  proxyPort: 8080
  proxyType: "HTTP"
  proxyEnabled: false

spring:
  datasource:
    url: jdbc:sqlite:dealbot.db
  flyway:
    user: sa
    password: sa
    schemas: main
    url: ${spring.datasource.url}
    locations: 'classpath:/db/init'
    enabled: true
    clean-on-validation-error: true